#!/usr/bin/env python3
"""Regenerate results/summary.md and results/summary_runs.csv from raw JSON.

Every table cell is the median over repetitions, with [min-max] where the
spread matters. Standard library only.
"""
import csv
import glob
import json
import os
import re
import statistics
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "results", "raw")
OUT_MD = os.path.join(ROOT, "results", "summary.md")
OUT_CSV = os.path.join(ROOT, "results", "summary_runs.csv")


def flat(d):
    s = d["stream_s"]
    return {
        "label": d["label"],
        "interval_us": d["config"]["interval_us"],
        "batch": d["config"]["batch"],
        "work_us": d["config"]["work_ns"] / 1000,
        "policy": d["config"]["policy"],
        "stream_s": s,
        "requested_hz": d["requested_rate_hz"],
        "achieved_hz": d["achieved_rate_hz"],
        "overruns": d["kernel_stats"]["timer_overruns_run"],
        "overruns_per_s": d["kernel_stats"]["timer_overruns_run"] / s,
        "received": d["received"],
        "driver_dropped": d["driver_dropped"],
        "app_dropped": d["app_dropped"],
        "shutdown_discarded": d["shutdown_discarded"],
        "reads_per_s": d["reads"] / s,
        "records_per_read": d["received"] / d["reads"] if d["reads"] else 0,
        "proc_cpu_pct": d["cpu"]["process_pct_of_one_cpu"],
        "proc_cpu_s": d["cpu"]["user_s"] + d["cpu"]["sys_s"],
        "producer_cpu_pct": 100 * d["cpu"]["producer_s"] / s,
        "procstat_cpu_s": d["cpu"]["procstat_util_pct"] / 100 * d["ncpu"] * d["wall_s"],
        "read_p50_us": d["read_latency_ns"]["p50"] / 1e3,
        "read_p95_us": d["read_latency_ns"]["p95"] / 1e3,
        "read_p99_us": d["read_latency_ns"]["p99"] / 1e3,
        "read_max_us": d["read_latency_ns"]["max"] / 1e3,
        "worker_p50_us": d["worker_latency_ns"]["p50"] / 1e3,
        "worker_p99_us": d["worker_latency_ns"]["p99"] / 1e3,
        "jitter_p50_us": d["jitter_ns"]["p50"] / 1e3,
        "jitter_p99_us": d["jitter_ns"]["p99"] / 1e3,
        "ok": d["ok"],
    }


def load():
    runs = defaultdict(lambda: defaultdict(list))
    rows = []
    for path in sorted(glob.glob(os.path.join(RAW, "*", "*_rep*.json"))):
        exp = os.path.basename(os.path.dirname(path))
        cfg = re.sub(r"_rep\d+\.json$", "", os.path.basename(path))
        with open(path) as f:
            r = flat(json.load(f))
        r["experiment"], r["config"] = exp, cfg
        r["rep"] = int(re.search(r"_rep(\d+)", path).group(1))
        runs[exp][cfg].append(r)
        rows.append(r)
    return runs, rows


def med(rs, k):
    return statistics.median(r[k] for r in rs)


def rng(rs, k, fmt="{:.0f}"):
    v = [r[k] for r in rs]
    m = statistics.median(v)
    if len(v) == 1:
        return fmt.format(m)
    return f"{fmt.format(m)} [{fmt.format(min(v))}-{fmt.format(max(v))}]"


def table(header, lines):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in l) + " |" for l in lines]
    return "\n".join(out)


def order(cfgs, exp):
    if exp == "rate":
        return sorted(cfgs, key=lambda c: -int(c[2:]))
    if exp == "batch":
        return sorted(cfgs, key=lambda c: int(c[1:]))
    if exp == "load":
        return sorted(cfgs, key=lambda c: (int(re.match(r"w(\d+)", c).group(1)), c))
    return sorted(cfgs)


def main():
    runs, rows = load()
    env = {}
    ep = os.path.join(RAW, "environment.json")
    if os.path.exists(ep):
        with open(ep) as f:
            env = json.load(f)
    md = ["# vsensor benchmark summary (generated by bench/summarize.py)", ""]
    if env:
        md += [f"- kernel `{env.get('kernel')}` ({env.get('machine')}), {env.get('nproc')} vCPUs, "
               f"{env.get('mem_total')}, virt: {env.get('virt')}, clocksource: {env.get('clocksource')}, "
               f"{env.get('hz')}",
               f"- module params: {env.get('module_params')}",
               f"- code revision: `{env.get('git_rev')}`{' (dirty)' if env.get('git_dirty') else ''}, "
               f"{env.get('gcc')}, collected {env.get('date_utc')}", ""]
    nreps = {len(v) for e in runs.values() for v in e.values()}
    md += [f"Repetitions per configuration: {sorted(nreps)}. Cells: median [min-max].",
           f"All runs passed the logger's accounting checks: {all(r['ok'] for r in rows)}.", ""]

    if "rate" in runs:
        md += ["## Sample-rate ladder (batch 64, 2 workers, no consumer work)", ""]
        lines = []
        for c in order(runs["rate"], "rate"):
            rs = runs["rate"][c]
            lines.append([f"{med(rs, 'requested_hz'):.0f}", rng(rs, "achieved_hz"),
                          rng(rs, "overruns_per_s", "{:.1f}"), f"{med(rs, 'driver_dropped'):.0f}",
                          rng(rs, "jitter_p50_us", "{:.1f}"), rng(rs, "jitter_p99_us", "{:.1f}"),
                          rng(rs, "read_p50_us", "{:.1f}"), rng(rs, "read_p95_us", "{:.1f}"),
                          rng(rs, "read_p99_us", "{:.1f}"), rng(rs, "proc_cpu_pct", "{:.1f}"),
                          rng(rs, "producer_cpu_pct", "{:.2f}")])
        md += [table(["requested Hz", "achieved Hz", "timer overruns/s", "driver drops",
                      "jitter p50 us", "jitter p99 us", "latency p50 us", "latency p95 us",
                      "latency p99 us", "logger CPU % (1 CPU)", "producer CPU %"], lines), ""]

    if "batch" in runs:
        md += ["## Read batch size at 20 kHz (2 workers, no consumer work)", ""]
        lines = []
        for c in order(runs["batch"], "batch"):
            rs = runs["batch"][c]
            lines.append([f"{med(rs, 'batch'):.0f}", rng(rs, "reads_per_s"),
                          rng(rs, "records_per_read", "{:.2f}"), rng(rs, "proc_cpu_pct", "{:.1f}"),
                          rng(rs, "read_p50_us", "{:.1f}"), rng(rs, "read_p99_us", "{:.1f}"),
                          rng(rs, "worker_p99_us", "{:.1f}"), f"{med(rs, 'driver_dropped'):.0f}"])
        md += [table(["max records/read", "read() calls/s", "records/read", "logger CPU %",
                      "latency p50 us", "latency p99 us", "worker latency p99 us", "driver drops"],
                     lines), ""]

    if "load" in runs:
        md += ["## Consumer load at 10 kHz (2 workers, batch 64, queue 64 batches)", ""]
        lines = []
        for c in order(runs["load"], "load"):
            rs = runs["load"][c]
            lines.append([f"{med(rs, 'work_us'):.0f}", rs[0]["policy"], rng(rs, "received"),
                          rng(rs, "app_dropped"), rng(rs, "driver_dropped"),
                          rng(rs, "read_p99_us", "{:.1f}"), rng(rs, "worker_p99_us", "{:.1f}"),
                          rng(rs, "proc_cpu_pct", "{:.1f}")])
        md += [table(["work us/record", "queue-full policy", "received", "app drops",
                      "driver drops", "read latency p99 us", "worker latency p99 us",
                      "logger CPU %"], lines), ""]

    if "cpuacct" in runs:
        md += ["## CPU accounting cross-check (rusage vs tick-sampled /proc/stat)", ""]
        lines = []
        for c in order(runs["cpuacct"], "cpuacct"):
            rs = runs["cpuacct"][c]
            lines.append([f"{med(rs, 'interval_us'):.0f}", rng(rs, "proc_cpu_s", "{:.3f}"),
                          rng(rs, "procstat_cpu_s", "{:.3f}"),
                          f"{100 * med(rs, 'procstat_cpu_s') / med(rs, 'proc_cpu_s'):.0f}%"])
        md += [table(["interval us", "logger CPU-s (rusage)", "whole-system busy CPU-s (/proc/stat)",
                      "/proc/stat as % of rusage"], lines), ""]

    with open(OUT_MD, "w") as f:
        f.write("\n".join(md))
    with open(OUT_CSV, "w", newline="") as f:
        keys = ["experiment", "config", "rep"] + [k for k in rows[0] if k not in
                                                  ("experiment", "config", "rep")]
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {OUT_MD} and {OUT_CSV} ({len(rows)} runs)")


if __name__ == "__main__":
    main()
